swagger: "2.0"
info:
  title: "Promotion Management Services"
  description: "Promotion management services for Simple and Buy Get promotions"
  version: "1.0.0"
  

tags:
- name: ""
  description: ""
  externalDocs:
    description: ""
    url: "http://someURL"

#######################################################################################
#                      Host , Basepath , Schemes , Content Types                                                     #
#######################################################################################
host: "localhost"

basePath: "/promoServices/v1"

schemes:
- "https"
- "http"

produces:
    - application/json

consumes:
    - application/json

#######################################################################################
#                      Security                                                       #
#######################################################################################
securityDefinitions:
    API Key:
        type: basic
        description: consumer should present api key and secret as part of standard http authorization header 
        
security:
    - API Key: []

#######################################################################################
#                      Parameters                                                     #
#######################################################################################
parameters:
    x-appCorelationId:
        name: x-appCorelationId
        in: header
        description: Used to trace a request
        type: string
        required: true
    x-userId:
        name: x-userId
        in: header
        description: user invoking API
        type: string
        required: false
    x-authorization:
        name: x-authorization
        in: header
        description: user auth
        type: string
        required: false        
    applicationId:
        name: applicationId
        in: query
        description: Unique application identifier
        type: string
        required: true    
#######################################################################################
#                      PATHS                                                          #
#######################################################################################
paths:
  
  /promotion/createSimple:
    post:
      tags:
      - "Create Simple Promotion"
      summary: "Create Simple Promo"
      description: "Create Simple Promo"
      operationId: "createSimplePromo"
      parameters:
       - $ref: '#/parameters/x-appCorelationId'
       - $ref: '#/parameters/x-authorization'
       - $ref: '#/parameters/applicationId'
       - in: "body"
         name: "SimplePromotionRequest"
         description: "Request object that contains SimplePromo payload"
         required: true 
         schema:
           $ref: "#/definitions/SimplePromoRequest"
      
      responses:
        204:
          $ref: "#/responses/204CreateSimplePromoSuccessResponse"
        
        400:
          $ref: "#/responses/400ErrorResponse"
        404:
          $ref: "#/responses/404ErrorResponse"
        500:
          $ref: "#/responses/500ErrorResponse"
   
  /healthcheck:
    get:
        tags:
            - HealthCheck
        description: heartbeat check of api health
        operationId: getHealthCheckStatus
        responses:
            200:
                $ref: '#/responses/200HealthCheckResponse'
#######################################################################################
#                      Responses                                                      #
#######################################################################################
responses:
    204CreateSimplePromoSuccessResponse:
        description: OK  
                                
    400ErrorResponse:
        description: |
            _Bad Request_
            
            Possible errors
            
            | Error Code | Error Message | Error Description |
            | ---------- | ------------- | ----------------- |
            | 8001       | Invalid input | Parameter missing {0} |
            
        schema:
            type: object
            properties:
                result:
                    type: object
                    properties:
                           errors:
                               type: array
                               items:
                                   $ref: '#/definitions/Error'
                                   
            example:
                result:
                    errors:
                        - code: 1600
                          message: 'Required Header params are missing'
                          details: 'Missing required header param - x-messageId'
    
    404ErrorResponse:
        description: |
            _Resource NOT Found_
            
            Possible errors
            
            | Error Code | Error Message | Error Description |
            | ---------- | ------------- | ----------------- |
            | 8005       | Submission not found | SubmissionId not found in provider system |
            
        schema:
            type: object
            properties:
                result:
                    type: object
                    properties:
                           errors:
                               type: array
                               items:
                                   $ref: '#/definitions/Error'
                                   
            example:
                result:
                    errors:
                        - code: 8005
                          message: 'Submission not found'
                          details: 'SubmissionId not found'
                          
    500ErrorResponse:
        description: |
            _Internal Server Error_
            
            Possible errors
            
            | Error Code | Error Message | Error Description |
            | ---------- | ------------- | ----------------- |
            | 10001       | ISE | Unknown error |
            | 10002       | ISE | Unknown error {0} |
            | 10300       | ISE | Unknown error |
            | 10301       | ISE | Unknown error |
            | 10302       | ISE | Unknown error |
            
        schema:
            type: object
            properties:
                result:
                    type: object
                    properties:
                           errors:
                               type: array
                               items:
                                   $ref: '#/definitions/Error'
                                   
            example:
                result:
                    errors:
                        - code: 10001
                          message: 'Internal Server Error'
                          details: 'Unkknown internal Technical error'
    
    200HealthCheckResponse:
        description: Healthcheck status 
        schema:
            $ref: '#/definitions/HealthcheckStatus'
#######################################################################################
#                      Model Definitions                                                     #
#######################################################################################

definitions:
    
    HealthcheckStatus:
        description: healthcheck status
        properties:
            status:
                type: string
                enum:
                    - success
                    
    SimplePromoRequest:
        description: Simple Promotion payload  
        type: object
        properties:
            promoId:
                description: type of task
                type: string
            promoDescription:
                type: string
                description: Promotion Details
            promoType:
                description: Type of Promotion 
                type: string
                enum:
                    - SIMPLE
                    - BUYGET
                    - THRESHOLD
             
             
                
    Error:
        description: This is an important object  
        type: object
        required:
            - code
            - message
        properties:
            code:
                description: Error code
                type: integer
                format: int32
            message:
                description: Error message 
                type: string            
            details:
                description: Detailed information about the error 
                type: string
